chore(#issue-17): bump nodejs version
university-of-york/aws-cdk-deploy-action pull request #20
Opened 2020-11-25 16:59 UTC by natseg

As referenced in issue #17, it is not currently possible to use the action using `@v1` in a github workflow.
The current set-up requires using fully qualified tags i.e. `v1.0.1`

This patch fixes this issue by adding a node hook to a success release.
It is supposed to delete existing tag with name `vn` – where `n` is the current major part in package.json's version.
It adds the tag again to the latest commit.
It pushes the tags to origin.

2020-11-25 17:05 UTC, natseg commented on dist/index.js
>  module.exports.MaxBufferError = MaxBufferError;
the dist folder rebuilds on any *js* file changes, maybe something to fix for later but not an issue per se?

2020-11-26 08:20 UTC, ben-eb requested changes
Nice work, if you could fix up the unassigned `require` call please I think it looks good to ship! 🚀

2020-11-26 08:20 UTC, ben-eb commented on scripts/tag-last-as-major.test.js
> +    require('./tag-last-as-major'); // eslint-disable-line import/no-unassigned-import
Instead of this could we separate the API logic and test that separately please? This could be a function called `moveGitTag`:

```js
const moveGitTag = async () => {
    const version = getCurrentVersion();

    if (!version) {
        throw new Error('Could not find version.');
    }

    const repository = buildRepoUrl();
    const tagName = `v${version}`;
    await execa('git', ['push', repository, '--delete', tagName]);
    await execa('git', ['tag', '-f', tagName]);
    await execa('git', ['push', repository, 'main', '--tags']);
};
```

Your CLI logic becomes:

```js
#!/usr/bin/env node

const moveGitTag = require('./move-git-tag');

moveGitTag().catch((error) => {
    console.error(error);
    process.exitCode = 1;
});
```

And we don't need to do an unassigned `require` call because loading `moveGitTag` won't produce any side effects. 🙂 

As a small bonus we don't need to introduce an artificial delay there either! 🎉

2020-11-30 09:57 UTC, natseg commented on scripts/tag-last-as-major.test.js
> +    require('./tag-last-as-major'); // eslint-disable-line import/no-unassigned-import
Sounds good to me! Thanks a lot! Will apply.

2020-12-04 10:37 UTC, natseg commented on scripts/tag-last-as-major.test.js
> +    require('./tag-last-as-major'); // eslint-disable-line import/no-unassigned-import
Think I have applied it and it looks much better thanks!

2020-12-04 12:01 UTC, ben-eb approved these changes
Looks great, thanks so much for making those changes! 🕺

2020-12-08 11:03 UTC, merged

2020-12-08 11:05 UTC, ESG-Jelly-Beans-Deploy commented
:tada: This PR is included in version 1.1.1 :tada:

The release is available on [GitHub release](https://github.com/university-of-york/aws-cdk-deploy-action/releases/tag/v1.1.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: