feat: Allow skipping `cdk bootstrap`
university-of-york/aws-cdk-deploy-action pull request #21
Opened 2020-11-27 15:34 UTC by rickselby

Most of our cdk pipelines don't need the bootstrapped resources, so it would be useful to optionally skip the bootstrap step.

Caveat: I don't write a lot of javascript, certainly nothing like this, so if I've gone about this the wrong way, I apologise - let me know what needs changing and I'll make the required tweaks.

2020-11-30 09:08 UTC, IPWright83 approved these changes
Looks fine by me :)

2020-11-30 09:24 UTC, ioannisGiak89 commented
Hi @rickselby, when do you actually need to run bootstrap and when not?

2020-11-30 09:53 UTC, natseg requested changes
Very good work, thank you so much, just a small thing to fix in the test! @rickselby 
I appreciate that you've made this a non-breaking change :star:

2020-11-30 09:53 UTC, natseg commented on src/cdkCommands.test.js
> +        expect(execa.mock.calls[2]).toMatchSnapshot();
So for this additional test, we need to take into account that `jest` keeps track of the mock calls unless we explicitly clear then in a [hook](https://jestjs.io/docs/en/setup-teardown#repeating-setup-for-many-tests).
```suggestion
   beforeEach(() => jest.clearAllMocks()) // on line 7
```

```suggestion
    expect(execa).toHaveBeenCalledTimes(1);
	expect(execa.mock.calls[0]).toMatchSnapshot();
```

2020-11-30 10:21 UTC, rickselby commented on src/cdkCommands.test.js
> +        expect(execa.mock.calls[2]).toMatchSnapshot();
Thanks, that's much better!

2020-11-30 10:23 UTC, rickselby commented
> Hi @rickselby, when do you actually need to run bootstrap and when not?

I don't think we ever actually run bootstrap - we're using cdk to deploy infrastructure, rather than apps.

2020-11-30 11:10 UTC, IPWright83 commented on src/cdkCommands.test.js
> +        expect(execa.mock.calls[2]).toMatchSnapshot();
Doh, sorry I missed that @natseg

2020-11-30 11:10 UTC, natseg approved these changes
Nice one, thanks!

2020-11-30 11:15 UTC, natseg requested changes
I don't want to block this but as a failsafe @ben-eb did spot (good spot) the  changes to package-lock... I wonder what happened there? What happens when discarding changes to it and running `npm ci`? Sorry for missing it.

2020-11-30 11:34 UTC, rickselby commented
That was a mistake, I think I have a newer version of node / npm that wanted to make the changes. I kept it out of the first commit but it slipped through later.

2020-11-30 12:03 UTC, natseg approved these changes
I think this time, we are good! Thanks so much for your patience 👍

2020-12-01 10:57 UTC, merged

2020-12-01 11:00 UTC, ESG-Jelly-Beans-Deploy commented
:tada: This PR is included in version 1.1.0 :tada:

The release is available on [GitHub release](https://github.com/university-of-york/aws-cdk-deploy-action/releases/tag/v1.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: